<?php 
echo "<a href=\"ControllerUser.php?action=insert\">Insert</a>";
        echo "<table border=1>";
        foreach ($users as $key => $user)
        {
            // Para cada usuario una fila
            // Para cada elemento una columna
            $user = explode("|", $user);
            echo "<tr>";
            foreach ($user as $value)
            {
                echo "<td>";
                echo $value;
                echo "</td>";
            }
            // Concatenar opcioens
                echo "<td>";
                echo "<a href=\"ControllerUser.php?action=update&id=".$key."\">update</a> | <a href=\"ControllerUser.php?action=delete&id=".$key."\">delete</a>";
                echo "</td>";
            echo "</tr>";
                    
            
        }
        echo "</table>";