<?php 
$users= $viewParams['users'];
?>
<div class="table-responsive">
    <a href="/user/insert">Insert</a>
    <table class="table table-striped" >
    <?php foreach ($users as $key => $user):?>
        <tr>
            <?php foreach ($user as $value):?>
            	<td><?=$value;?></td>
            <?php endforeach;?>
            <td>
                <a href="/user/update/id/<?=$user['iduser'];?>">update</a> | 
        	    <a href="/user/delete/id/<?=$user['iduser'];?>">delete</a>
            </td>
        </tr>
    <?php endforeach;?>
    </table>
</div>